name: shoes_app
description: UI to app
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  eva_icons_flutter: ^2.0.1
  get: ^3.24.0
  flutter_rating_bar: ^3.2.0+1
  flutter_spinkit: ^4.1.2+1
  google_fonts: ^1.1.1
  bot_toast: ^3.0.5
  rxdart: ^0.25.0
  flutter_slidable: ^0.5.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/brands/
    - assets/shoes/
    - assets/shoes/1/
    - assets/shoes/2/
    - assets/shoes/more_image/